# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.1

before_install:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

# Commands to be run before your environment runs.
before_script:
  - cp .env.travis .env
  - cd source
  - composer self-update
  - composer install

# commands to be run after environment runs
after_script:
  - vendor/bin/test-reporter


# Commands you want to run that will verify your build.
script: ./vendor/bin/phpunit  tests/

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always